version: 3
workdir: internal
allow:
  depOnAnyVendor: true
components:
  domain: { in: domain/** } 
  app:    { in: app/** }    
  infra:  { in: infra/** }  

deps:
  domain:
    mayDependOn:
      - domain
  app:
    mayDependOn:
      - domain
      - app
  infra:
    mayDependOn:
      - domain
      - app
      - infra